# Generated by Django 4.0.6 on 2022-07-25 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('desc', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Return Date')),
                ('qty', models.SmallIntegerField(default=1)),
                ('total_price', models.SmallIntegerField(default=0)),
                ('gear_item', models.ManyToManyField(to='main_app.gear_item')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gear_item')),
            ],
        ),
    ]
