# Generated by Django 4.0.6 on 2022-07-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gear_item_name_gear_item_price_gear_item_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_items', models.ManyToManyField(to='main_app.gear_item')),
            ],
        ),
    ]
