# Generated by Django 4.0.6 on 2022-07-27 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gear_item',
            field=models.ManyToManyField(related_name='gear_items', to='main_app.gear_item'),
        ),
    ]
