# Generated by Django 4.0.6 on 2022-07-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear_item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
    ]
