# Generated by Django 4.0.6 on 2022-07-23 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_remove_reservation_gear_items_reservation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Reservation_item',
        ),
    ]
