# Generated by Django 4.0.6 on 2022-07-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_gear_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear_item',
            old_name='image',
            new_name='image_url',
        ),
    ]
