# Generated by Django 4.0.6 on 2022-07-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_reservation_item_user_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_item',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.reservation'),
            preserve_default=False,
        ),
    ]
