# Generated by Django 4.0.6 on 2022-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_image_gear_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear_item',
            name='image_url',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
