# Generated by Django 4.0.6 on 2022-07-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_reservation_item_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation_item',
        ),
    ]
