# Generated by Django 4.0.6 on 2022-07-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_gear_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear_item',
            name='image_url',
        ),
    ]
