# Generated by Django 4.0.6 on 2022-07-23 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_reservation_total_remove_reservation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Return Date'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_item',
            field=models.ManyToManyField(to='main_app.gear_item'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
