# Generated by Django 4.0.6 on 2022-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_gear_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear_item',
            name='image_url',
            field=models.CharField(default='https://a-lodge.com/wp-content/uploads/A-Lodge_No_Location_Grey-1200x221.png', max_length=500),
        ),
    ]
