# Generated by Django 4.0.6 on 2022-07-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_reservation_end_date_reservation_gear_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qty',
            field=models.SmallIntegerField(default=0),
        ),
    ]
