# Generated by Django 4.0.6 on 2022-08-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_comment_post_topic_delete_photo_post_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
