# Generated by Django 4.0.6 on 2022-08-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_author_comment_user_rename_author_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='title',
        ),
    ]
