# Generated by Django 4.0.6 on 2022-07-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_reservation_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='gear_item',
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_item',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.gear_item'),
            preserve_default=False,
        ),
    ]
