# Generated by Django 4.0.6 on 2022-07-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_reservation_gear_item_reservation_gear_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='gear_item',
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_item',
            field=models.ManyToManyField(to='main_app.gear_item'),
        ),
    ]
