# Generated by Django 4.0.6 on 2022-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_reservation_gear_item_reservation_gear_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear_item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
