# Generated by Django 4.0.6 on 2022-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_gear_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
