# Generated by Django 4.0.6 on 2022-07-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_reservation_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('gear_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.gear_item')),
            ],
        ),
        migrations.AlterField(
            model_name='gear_item',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
